---
- name: Init BDR
  command: psql -U  {{ postgresql_user }} -d {{ postgresql_databases[0].name }} -c "{{ item }}"
  with_items: {{ bdr_init }}

- name: Create BDR Main Node
  command: psql -U  {{ postgresql_user }} -d {{ postgresql_databases[0].name }} -c "{{ init_main_bdr }}"
  when: "'node' not in group_names"

- name: Create BDR  Node
  command: psql -U  {{ postgresql_user }} -d {{ postgresql_databases[0].name }} -c "{{ init_node_bdr }}"
  when: "'main' not in group_names"
