---
# Ansible playbook for a Drupal LAMP server.
#
# @author Jeff Geerling (2014).

- hosts: pg01a
  gather_facts: yes

  pre_tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install EPEL repo.
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present

    - name: Import EPEL GPG key.
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: Install common packages
      yum:
        name: ['vim', 'curl', 'git', 'htop', 'mc', 'python-pip', 'unzip', 'bash-completion']
        state: latest

    - name: Add repository for later versions of Postgres.
      yum:
        name: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-redhat11-11-2.noarch.rpm
        state: present
